ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy

.Technology decisions

|===
|Technology|Description
| _Git_ | _Software version control system_ 
| _GitHub_ | _Cloud-based service that hosts the aforementioned version control system, Git._ 
| _React_ | _JavaScript library that allows us to create interactive user interfaces in a simple way. It is based on components._ 
| _MongoDB_ | _Open source, document-oriented database system_ 
| _Docker_ | _A tool that makes it easy to create, deploy and run applications using containers. Containers allow you to package an application with all the parts you need, such as libraries and other dependencies, and deploy it as a single package._ 
| _API_ | _Se usará una API externa para mostrar el mapa_ 
| _Javascript_ | _An interpreted programming language based on prototypes, imperative and dynamic. We will use it on both frontend and backend._
| _CSS_ | _A graphic programming language oriented to define the repesentation of a document._
|===

.Decisions on how to achieve key quality goals

* Usability: the team will take care to design a clear and accessible interface for any user. This will be based on web usability standards.

* Privacy: users' private information will be stored in such a way that it will not be accessible to external factors.

* Security: we will take care to implement all the measures we deem appropriate to secure our application.

* Testability: this is an important quality objective to ensure that the software is reliable, robust and error-free. It is important to implement appropriate software development practices, such as separation of concerns and modular design.

.Relevant Organizational Decisions

Regarding the organization within the team, we have taken the following decisions:

* Extraordinary meetings, we do them through Discord or Microsoft Teams, because all team members are familiar with that tool.

* Communication between team members occurs mainly through a WhatsApp group, but any problem that arises is also reflected as an issue in Github.

* We use a Kanban board within github to have well organized and in a very clear way the tasks that each team member has to perform/is performing.


[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape system architecture. It includes

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the foundation for many other detailed decisions or implementation rules.

.Form
Keep the explanations of such key decisions short.

Motivate what was decided and why it was decided that way,
based upon problem statement, quality goals and key constraints.
Refer to details in the following sections.


.Further Information

See https://docs.arc42.org/section-4/[Solution Strategy] in the arc42 documentation.

****
