ifndef::imagesdir[:imagesdir: ../images]

[[section-concepts]]
== Cross-cutting Concepts


=== Domain model

* Hacer el diagrama del dominio


=== Privacity
Security is a very important concept in the context of a system. Since we manage user information, it is important to ensure that the information is secure and that the system is not compromised.

In addition, we add back-end security to prevent unauthorized requests to the RestAPI, as well as to prevent the execution of malicious code.

=== Usability
Usability is a fundamental aspect of any application, as it determines the ease and efficiency with which users can interact with it. To ensure the usability of our application, we have followed a series of specific practices and techniques.

We have thoroughly researched user needs and expectations, which has allowed us to design an intuitive and easy-to-use user interface.

=== Maintainability
The maintainability of the application is an important section since it is necessary that the code is easily modifiable in case in the future we are asked for new features to implement.

We are going to use React, which is a framework that facilitates interactivity with the user interface, so it is important to reach users.


=== Testeability
As a best practice, throughout development, we will subject our code to multiple unit tests, in order to ensure the robustness and effectiveness of our product before it is deployed on the web. As well, we will  test the functionality of the whole app itself, so that the user experience is the best possible.
